### ISSUE TITLE
webpack live reload when module changes

### ISSUE THREAD

**Issue by andreyvolokitin** [posthtml/posthtml-modules#33]
There is no recompiling and no live reload of a page when module contents changes

**Comment by michael-ciniawsky** [comment]
Not supported by this plugin atm, but definitely has high priority

**Comment by equinusocio** [comment]
No update on this?

**Comment by Scrum** [comment]
@equinusocio Hi, until I really understand the relationship between this package and the webpack, could you tell me more in detail or give a real example or problem?

**Comment by equinusocio** [comment]
For sure!

This is my seimplified example:

**src/modules/module.html**
```html
<div>I'm a module! <content></content></div>
```

**src/index.html**
```html
<!-- ... all the html stuff -->
<module href="/modules/module.html">Nice!</module>
```

**posthtml.config.js**
```js
module.exports = {
  'plugins': {
    'posthtml-modules': {
      root: './src'
    }
  }
}
```

This is my parcel **1.11.0** scripts:

```json
{
  "dev": "parcel src/**/*.html --open",
}
```

When running the parcel dev server the page is reloaded only if i change **index.html** and not **module.html** (or any module file)

**Comment by Scrum** [comment]
@equinusocio Hi, unfortunately I have not found information about the parsing of values that are patterns such as `**/*.ext`.

but that's what I noticed if we have such a structure:

**project**
```
root
- src
-- index.html
-- module
--- module.html
```
**cli.js**
```js
#!/usr/bin/env node
console.log(process.argv.slice(2));
```

if run like npm-script `"dev": "cli src/**/*.html"`  then we get
```console
[ 'src/modules/module.html' ]
```


if run like npx `npx cli src/**/*.html`  then we get
```console
[ 'src/index.html', 'src/modules/module.html' ]
```

**Comment by toytonic** [comment]
Same problem here. Changes in any module html file does not trigger a reload. But: Changes are visible after change in a 'main' html file.

**Comment by Scrum** [comment]
due to the fact that the list does not include all files, see above

**Comment by c01nd01r** [comment]
I use this workaround for Parcel:
https://github.com/pugson/parcel-static-template/blob/master/tools/watcher.js#L36-L57

**Comment by thewebartisan7** [comment]
Why posthtml-include and extends works fine while not for this plugin the live reload?

**Comment by ecmel** [comment]
FYI, https://github.com/posthtml/posthtml-include works fine with parcel cache
