### ISSUE TITLE
Nested module tags yield incorrect results

### ISSUE THREAD

**Issue by bsonntag** [posthtml/posthtml-modules#43]
When using a `<module>` inside another `<module>`'s content, the nested module will have duplicate markup.

To be clear, I'm trying to do something like this:

```html
<module href="/layout.html">
  <h1>Hello world!</h1>

  <module href="/button.html">
    Click me
  </module>
</module>
```

Reproduction here: https://github.com/bsonntag/posthtml-modules-bug-repro

**Comment by bsonntag** [comment]
One thing that seems to fix this is to move the replacing of `<content>` to be after the recursive call. Can I submit a PR with this fix?

**Comment by cossssmin** [comment]
> Can I submit a PR with this fix?

Of course, feel free to submit a PR (with tests) 🙂

**Comment by anikethsaha** [comment]
@bsonntag whats the current output ?

**Comment by cossssmin** [comment]
@anikethsaha currently, given these components:

*layout.html*

```html
<div>
  <content></content>
</div>
```

*button.html*

```html
<button>
  <content></content>
</button>
```

... this:

```html
<module href="layout.html">
  Layout
  <module href="button.html">Button</module>
</module>
```

... results in this:

```html
<div>
  Layout
  <button></button><button>Button</button>
</div>
```

**Comment by anikethsaha** [comment]
umm, yea seems like a bug,

Thanks, I reviewed the PR.

**Comment by Scrum** [comment]
@bsonntag publish v0.6.1
