### ISSUE TITLE
Nesting randomly fails when locals are provided

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-modules#51]
https://github.com/posthtml/posthtml-modules/blob/c182bae68c0c31db257be929c2b7628ad715dbbb/test/test.js#L33-L38

Change that test to:

```
<module href="./tree.spec/layout.html" locals='{"foo": "bar"}'>
  Test
  <module href="./tree.spec/_/button.html">Button</module>
</module>
```

Result:

```html
<div class="container">
  Test
  <module href="./tree.spec/_/button.html">Button</module>
</div>
```

Try to use that in the nesting test and run it multiple times - most of the time it fails to render the `button.html` module and it outputs the module tag as it was nested. 

But sometimes - apparently randomly - it works 🤷‍♂️

Originally reported in https://github.com/maizzle/framework/issues/369

**Comment by Scrum** [comment]
@cossssmin Thank you, this is a very interesting quest that makes me think

**Comment by Scrum** [comment]
@cossssmin publish v0.6.3

**Comment by cossssmin** [comment]
It's breaking the build now, I'm getting a `Can’t process contents in sync mode because of async plugin` error. See my setup [here](https://github.com/maizzle/framework/blob/master/src/generators/posthtml.js).

**Comment by cossssmin** [comment]
Yeah, so removing `posthtml-fetch` gets it working again. But this isn't an option for me, how can we use it with an async plugin?

**Comment by Scrum** [comment]
Yes, I had to make everything synchronous. the sequence of the matched nodes was important here

https://github.com/posthtml/posthtml-modules/blob/b7e19c8eed4382f105509bbfa8eab413cea8ddb7/index.js#L94-L98

**Comment by cossssmin** [comment]
Also, if we set `initial: true`, shouldn't this component:

```html
TEXT IN COMPONENT: {{ foo }}
<content></content>
```

... when used like this:

```html
<module href="test.html" locals='{"foo": "bar"}'>
  parent
  <module href="test.html">
    child
  </module>
</module>
```

... result in this?

```html
TEXT IN COMPONENT: bar
parent
TEXT IN COMPONENT: bar
child
```

It currently renders:

```html
TEXT IN COMPONENT: bar
parent
TEXT IN COMPONENT: undefined
child
```

And without `initial: true` it renders:

```html
TEXT IN COMPONENT: bar
parent
TEXT IN COMPONENT: {{ foo }}
child
```

**Comment by Scrum** [comment]
@cossssmin If it's not difficult to create a new task with a tie to this, I'll try to come up with something

**Comment by cossssmin** [comment]
Cool, will lock Maizzle to `posthtml-modules@0.6.2` for now since that fetch plugin is an important feature.

**Comment by Scrum** [comment]
Now I will reverse the changes and only then I will think about solving this problem

**Comment by boreenberg** [comment]
Hi @Scrum - curious to know if you had a chance to look further into this issue?

**Comment by Scrum** [comment]
> Hi @Scrum - curious to know if you had a chance to look further into this issue?

Hello, unfortunately I have already lost the context when solving other problems, if you have solutions, make a PR and I will gladly consider it.
