### ISSUE TITLE
Is there any way to ignore a locals expression?

### ISSUE THREAD

**Issue by herrherrmann** [posthtml/posthtml-modules#55]
I’d like to use locals inside my modules but keep some of the placeholder syntax around (for another post-processing step outside of posthtml).

# Example:
**Input:**
```html
<!-- my-partial.html -->
<div>{{title}}</div>

<!-- index.html -->
<module href="my-partial.html" locals='{"title": "Here’s my title"}'></module>
@{{ username }} <!-- ...or {{{username}}} or \{{username}} -->
```

**Expected output:**
```html
<div>Here’s my title</div>
{{ username }}
```

**Actual output:**
```html
<div>Here’s my title</div>
undefined
```

[posthtml-expressions](https://github.com/posthtml/posthtml-expressions#ignoring-expressions) supports the `@{{}}` syntax to achieve this but posthtml-modules doesn’t seem to interpret them accordingly. Are there any considerations to add this feature or possible workarounds with the current version?

Thanks in advance for any help!

**Comment by Scrum** [comment]
Hi, [ignoring-expressions](https://github.com/posthtml/posthtml-expressions#ignoring-expressions) or [ignored-tag](https://github.com/posthtml/posthtml-expressions#ignored-tag)

**Comment by herrherrmann** [comment]
Thanks for the headsup! Interestingly, the only thing that worked for me now was a _combination_ of the two syntaxes:

### ❌ Ignored expression does not work
```html
@{{ username }}
```

**Output:**
```html
undefined
```

### ❌ Ignored tag does not work
```html
<raw>{{ username }}</raw>
```

**Output:**
```html
undefined
```


### ✅ Both together are working
```html
<raw>@{{username}}</raw>
```

**Output:**
```html
{{username}}
```
