### ISSUE TITLE
locals option

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-modules#56]
I think we could have a `locals` option that, when provided, would be merged with any locals from the `locals=""` attribute.

So that you could pass a data object that you might already have in your build workflow:

```html
<module href="module.html" locals='{"year": "2021"}'></module>
```

```html
<!-- module.html -->

{{ year }}

{{ foo }}
```

```js
const data = {foo: 'bar'}

require('posthtml-modules')({
  locals: data,
  // ... other posthtml-modules options
})
```

Result:

```html
2021

bar
```

What do you think @Scrum?

**Comment by Scrum** [comment]
looks good
